name: Scala CI
 
on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - 'version.sbt'
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
 
permissions:
  contents: read
  packages: read
 
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Setup sbt launcher
        uses: sbt/setup-sbt@v1
      - name: Run scalafmtCheckAll
        run: sbt +scalafmtCheckAll
      - name: Run scalafixAll --check
        run: sbt "+scalafixAll --check"
      - name: Run tests
        run: make test-all
