name: Release

on:
  workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v4
    - run: git config --global user.email "gpp-informatics@broadinstitute.org"
    - run: git config --global user.name "GPP Informatics"
    - uses: jrouly/scalafmt-native-action@v3
      with:
        version: "3.8.3"
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'
    - name: Setup sbt launcher
      uses: sbt/setup-sbt@v1
    - run: sbt "scalafixAll --check"
    - name: Run tests
      run: make test-all
    - name: Release
      run: sbt "release cross with-defaults"
